name: My Caller

on:
    workflow_dispatch:

jobs:
    eval:
        uses: samuelchen/test/.github/workflows/test.yml@main

    report:
        runs-on: ubuntu-latest
        needs: eval
        steps:
            -   run: echo ${{ needs.job1.outputs.reports }}
