name: PR Caller1

on:
    workflow_dispatch:
    
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            -   name: Add comment to PR
                env:
                    URL: https://api.github.com/repos/samuelchen/test/issues/1/comments
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    curl \
                      -X POST \
                      $URL \
                      -H "Content-Type: application/json" \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      --data @- << EOF
                      {"data": "Eval type: retrieval"}
                      EOF
