name: Mixed

on:
    schedule:
        -   cron: '*/1 * * * *'

    workflow_dispatch:
        inputs:
            eval_type:
                description: 'agent/retrieval/plan_retrieval'
                default: 'retrieval'
                required: true
                type: string
            dataset:
                description: 'Dataset to evaluate on'
                default: 'simple'
                required: true
                type: string

jobs:
    eval:
        runs-on: ubuntu-latest
        outputs:
            report: ${{ steps.step1.outputs.delta_code }}
        env:
            EVAL_TYPE: ${{ inputs.eval_type }}
            DATASET: ${{ inputs.dataset }}
        steps:
            -   name: Run Eval
                id: step1
                run: |
                    CMD="echo 'first line of output "${{ inputs.eval_type }}" "${env}" "${DATASET}" '; echo 'second line of output'; echo '3rd line of output'"
                    delta=$(eval $CMD)
                    delta="${delta//'%'/'%25'}"
                    delta="${delta//$'\n'/'%0A'}"
                    delta="${delta//$'\r'/'%0D'}"
                    delta="${delta//$'"'/'\"'}"
                    echo "::set-output name=delta_code::$delta"

            -   name: Report
                id: report
                run: |
                    echo "${{ steps.step1.outputs.delta_code }}"
