name: PR Caller

on:
    pull_request:
        types:
            - labeled

jobs:
    eval:
        if: ${{ github.event.label.name == 'eval'}}
        uses: samuelchen/test/.github/workflows/test.yml@master
        with:
            eval_type: retrieval
            dataset: simple

    report:
        if: ${{ github.event.label.name == 'eval'}}
        runs-on: ubuntu-latest
        needs: eval
        steps:
            -   run: |
                    cat > report-data.json <<EOF
                    {
                        "data": "${{ needs.eval.outputs.report }}"
                    }
                    EOF
            -   name: Add comment to PR
                env:
                    URL: ${{ github.event.pull_request.comments_url }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    curl \
                    -X POST \
                    $URL \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    --data @report-data.json
