name: PR Caller

on:
    pull_request:
        types:
            - labeled

jobs:
    eval:
        if: ${{ github.event.label.name == 'eval'}}
        uses: samuelchen/test/.github/workflows/test.yml@master
        with:
            eval_type: retrieval
            dataset: simple

    report:
        if: ${{ github.event.label.name == 'eval'}}
        runs-on: ubuntu-latest
        needs: eval
        steps:
            -   run: echo "${{ needs.eval.outputs.report }}"
            -   run: echo "${{ github.event.pull_request.comments_url }}"
            -   name: Add comment to PR
                uses: actions/github-script@v6
                with:
                    script: |
                        github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: "${{ needs.eval.outputs.report }}"
                        })
