name: PR Caller

on:
    pull_request:
        types:
            - labeled

jobs:
    eval:
        if: ${{ github.event.label.name == 'eval'}}
        uses: samuelchen/test/.github/workflows/test.yml@master
        with:
            eval_type: retrieval
            dataset: simple

    report:
        if: ${{ github.event.label.name == 'eval'}}
        runs-on: ubuntu-latest
        needs: eval
        steps:
            -   run: echo "${{ needs.eval.outputs.report }}"
            -   run: echo "${{ github.event.pull_request.url }}"
            -   name: Add comment to PR
                env:
                    URL: ${{ github.event.pull_request.comments_url }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    curl \
                      -X POST \
                      $URL \
                      -H "Content-Type: application/json" \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      --data '{ "body": "${{ needs.eval.outputs.report }}" }'
