name: Schedule Call

on:
    schedule:
        -   cron: '*/1 * * * *'

jobs:

    eval:
        uses: samuelchen/test/.github/workflows/test.yml@master
        with:
            eval_type: retrieval
            dataset: simple

    report:
        env:
            TEST: ${{ github.event.inputs.test || aaa }}
        runs-on: ubuntu-latest
        needs: eval
        steps:
            -   run: echo "|${TEST}|${{ needs.eval.outputs.report }}"

